/** Machine-readable needs-review and warning codes for tax determination. */
export const TaxReviewReason = {
  MISSING_TAX_LOCATION: "MISSING_TAX_LOCATION",
  MISSING_TAX_CATEGORY: "MISSING_TAX_CATEGORY",
  NO_TAXABILITY_RULE: "NO_TAXABILITY_RULE",
  AMBIGUOUS_TAX_RULE: "AMBIGUOUS_TAX_RULE",
  NO_ACTIVE_TAX_RATE: "NO_ACTIVE_TAX_RATE",
  AMBIGUOUS_TAX_RATE: "AMBIGUOUS_TAX_RATE",
  INVALID_EXEMPTION: "INVALID_EXEMPTION",
  AMBIGUOUS_EXEMPTION: "AMBIGUOUS_EXEMPTION",
  EXPIRED_EXEMPTION: "EXPIRED_EXEMPTION",
  EXEMPTION_NEEDS_REVIEW: "EXEMPTION_NEEDS_REVIEW",
  UNSUPPORTED_CONFIGURATION: "UNSUPPORTED_CONFIGURATION",
  UNKNOWN_LOCAL_JURISDICTION: "UNKNOWN_LOCAL_JURISDICTION",
  FACT_DEPENDENT_CLASSIFICATION: "FACT_DEPENDENT_CLASSIFICATION",
  CROSS_STATE_SOURCING_REVIEW: "CROSS_STATE_SOURCING_REVIEW",
} as const;

export type TaxReviewReasonCode = (typeof TaxReviewReason)[keyof typeof TaxReviewReason];
