export const ExemptionReason = {
  AMBIGUOUS_EXEMPTION: "AMBIGUOUS_EXEMPTION",
  EXPIRED_EXEMPTION: "EXPIRED_EXEMPTION",
  FUTURE_EXEMPTION: "FUTURE_EXEMPTION",
  REVOKED_EXEMPTION: "REVOKED_EXEMPTION",
  REJECTED_EXEMPTION: "REJECTED_EXEMPTION",
  EXEMPTION_OUT_OF_JURISDICTION: "EXEMPTION_OUT_OF_JURISDICTION",
  EXEMPTION_OUT_OF_CATEGORY: "EXEMPTION_OUT_OF_CATEGORY",
  INCOMPLETE_EXEMPTION: "INCOMPLETE_EXEMPTION",
  EXEMPTION_NEEDS_REVIEW: "EXEMPTION_NEEDS_REVIEW",
  DUPLICATE_EXEMPTION: "DUPLICATE_EXEMPTION",
} as const;

export type ExemptionReasonCode = (typeof ExemptionReason)[keyof typeof ExemptionReason];
